const parks=[
	{
		name:'Arnada Park',
		address:`610 E 25th St.
Vancouver, WA 98663`,
		size:'3 acres',
        image:'playground1.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Bagley Community Park',
		address:`4607 Plomondon St.
Vancouver, WA 98661`,
		size:'15.3 acres',
        image:'playground2.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:true,
			restroom:true,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:true,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:true,
			discGolf:false,
		}
	},
	{
		name:'Beaver Marsh',
		address:`3915 NE 98th Ave.
Vancouver, WA 98662`,
		size:'32 acres',
        image:'trail2.webp',
		features:{
			benches:false,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Behrens Woods',
		address:`3005 SE Bella Vista Pl.
Vancouver, WA 98683`,
		size:'2 acres',
        image:'trail1.webp',
		features:{
			benches:false,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Bella Vista Park',
		address:`1911 SE Bella Vista Rd.
Vancouver, WA 98683`,
		size:'5.3 acres',
        image:'playground4.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Biddlewood Park',
		address:`SE Riveridge Dr.
Vancouver, WA 98683`,
		size:'7 acres',
        image:'playground5.webp',
		features:{
			benches:false,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Blandford Greenway',
		address:`N Blandford Dr.
Vancouver, WA 98661`,
		size:'20 acres',
        image:'trail2.webp',
		features:{
			benches:false,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Brickyard Park',
		address:`3120 Lincoln Ave.
Vancouver, WA 98660`,
		size:'2 acres',
        image:'playground6.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Burnt Bridge Creek School Park',
		address:`14619-A NE 49th St.
Vancouver, WA 98682`,
		size:'3.2 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:true,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Burnt Bridge Creek Trail',
		address:`1617 N Devine Rd.
Vancouver, WA 98661`,
		size:'not available',
        image:'paved3.webp',
		features:{
			benches:false,
			tables:true,
			playLawn:false,
			playground:false,
			pavedTrail:true,
			soccer:false,
			restroom:true,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Carl Gustafson Park',
		address:`200 N Nashville Way
Vancouver, WA 98664`,
		size:'3.4 acres',
        image:'playground8.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Carter Park',
		address:`3300 Columbia St.
Vancouver, WA 98660`,
		size:'0.7 acres',
        image:'playground9.webp',
		features:{
			benches:false,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Cascade Park',
		address:`13003 SE 7th St.
Vancouver, WA 98683`,
		size:'3.5 acres',
        image:'playground10.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Centerpointe Park',
		address:`8200 NE Pierce Dr.
Vancouver, WA 98662`,
		size:'8.7 acres',
        image:'playground11.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Clearmeadows Park',
		address:`17700 SE 24th St.
Vancouver, WA 98683`,
		size:'5.7 acres',
        image:'playground12.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Columbia Lancaster Park',
		address:`6000 Idaho St.
Vancouver, WA 98661`,
		size:'2.4 acres',
        image:'playground13.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Columbia River Renaissance Trail',
		address:`115 Columbia Way
Vancouver, WA 98661`,
		size:'not available',
        image:'trail1.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Countryside Park',
		address:`15204 NE 7th St.
Vancouver, WA 98684`,
		size:'2.3 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'David Douglas Park',
		address:`1016 N Garrison Rd.
Vancouver, WA 98664`,
		size:'not available',
        image:'playground1.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:true,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:true,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:true,
			tennis:false,
			softball:true,
			discGolf:false,
		}
	},
	{
		name:'Diamond Park',
		address:`14512 NE 32nd St.
Vancouver, WA 98682`,
		size:'5.3 acres',
        image:'playground2.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Discovery Historic Loop Trail',
		address:`115 SE Columbia Way
Vancouver, WA 98661`,
		size:'not available',
        image:'stanley-park.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:false,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'DuBois Park',
		address:`California St.
Vancouver, WA 98661`,
		size:'3.5 acres',
        image:'playground3.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Edgewood Park',
		address:`600 Edwards Ln.
Vancouver, WA 98661`,
		size:'3 acres',
        image:'playground4.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Ellen Davis Trail',
		address:`Saint James and NE Minnehaha St,
Vancouver, WA 98663`,
		size:'2 miles',
        image:'trail2.webp',
		features:{
			benches:false,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Ellsworth School Park',
		address:`512 SE Ellsworth Rd.
Vancouver, WA 98664`,
		size:'3 acres',
        image:'playground13.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:true,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Ellsworth Springs Park',
		address:`11120 SE 18th St.
Vancouver, WA 98664`,
		size:'not available',
        image:'playground5.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Endeavour Park',
		address:`2501 NE Four Seasons Ln.
Vancouver, WA 98684`,
		size:'2.5 acres',
        image:'playground6.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Esther Short Park',
		address:`605 Esther St.
Vancouver, WA 98660`,
		size:'5 acres',
        image:'esther-short-park.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:true,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Evergreen Highway Trail at Columbia Springs',
		address:`12208 SE Evergreen Hwy.
Vancouver, WA 98683`,
		size:'not available',
        image:'paved4.webp',
		features:{
			benches:false,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Evergreen Park',
		address:`3500 E 4th Plain Blvd.
Vancouver, WA 98661`,
		size:'4 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Father Blanchet Park',
		address:`7210 Louisiana Dr.
Vancouver, WA 98664`,
		size:'2.5 acres',
        image:'playground8.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Fir Garden Park',
		address:`4209 NE 155th Ave.
Vancouver, WA 98682`,
		size:'5 acres',
        image:'halfcourt.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Fircrest Park',
		address:`12100 NE 5th St.
Vancouver, WA 98684`,
		size:'5 acres',
        image:'playground10.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'First Place Park',
		address:`1499 NE 152nd Ave.
Vancouver, WA 98684`,
		size:'3.5 acres',
        image:'playground11.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Fisher Basin Community Park',
		address:`SE 192nd Ave.
Vancouver, WA 98607`,
		size:'12.3 acres',
        image:'playground12.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:true,
			restroom:true,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:true,
			skatePark:false,
			natureTrail:false,
			waterFountain:true,
			horseshoes:false,
			tennis:true,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Fisher\'s Creek Neighborhood Park',
		address:`18400 SE 42nd St.
Vancouver, WA 98683`,
		size:'1.9 acres',
        image:'playground13.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Forest Ridge Park',
		address:`9513 NE 16th St.
Vancouver, WA 98664`,
		size:'1.5 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Fort Vancouver National Historic Site',
		address:`612 E Reserve St.
Vancouver, WA 98661`,
		size:'not available',
        image:'fort-vancouver.webp',
		features:{
			benches:false,
			tables:true,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Franklin Park',
		address:`1315 NW 58th St.
Vancouver, WA 98663`,
		size:'12 acres',
        image:'playground1.webp',       
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Fruit Valley Park',
		address:`3200 Fruit Valley Rd.
Vancouver, WA 98660`,
		size:'6 acres',
        image:'playground2.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'General Anderson Park',
		address:`Texas Dr. & Burdick St.
Vancouver, WA 98661`,
		size:'1.9 acres',
        image:'playground3.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'George and Hazel Stein Park',
		address:`9800 NE 6th Cir.
Vancouver, WA 98664`,
		size:'0.77 acres',
        image:'trail2.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Gretchen Fraser Neighborhood Park',
		address:`516 SE 155th Ave.
Vancouver, WA 98684`,
		size:'2.2 acres',
        image:'playground4.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Hazel Hart Park',
		address:`2117 E 9th St.
Vancouver, WA 98661`,
		size:'0.2 acres',
        image:'playground5.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:true,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Hearthwood Park',
		address:`801 NE Hearthwood Blvd.
Vancouver, WA 98684`,
		size:'6.2 acres',
        image:'playground6.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:true,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Heritage Park',
		address:`2913 SE 170th Ave.
Vancouver, WA 98683`,
		size:'4.7 acres',
        image:'halfcourt2.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Hidden Park',
		address:`3810 Daniels St.
Vancouver, WA 98660`,
		size:'1.2 acres',
        image:'playground8.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Homestead Park',
		address:`1800 SE 160th Ave.
Vancouver, WA 98683`,
		size:'6.2 acres',
        image:'swings.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Ida Bell Jones Park',
		address:`1901-1999 E 35th St.
Vancouver, WA 98663`,
		size:'0.5 acres',
        image:'playground10.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:true,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Jaggy Road Park',
		address:`4500 NE 72nd Ave.
Vancouver, WA 98661`,
		size:'3.4 acres',
        image:'playground6.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'John and Margrette Coop Park',
		address:`NE 11th St at, NE 89th Ave.
Vancouver, WA 98664`,
		size:'3.5 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'John Ball Park',
		address:`West 23rd St. & Kauffman Ave.
Vancouver, WA 98660`,
		size:'not available',
        image:'playground11.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Kevanna Park',
		address:`10500 NE 47th St.
Vancouver, WA 98682`,
		size:'6.3 acres',
        image:'playground12.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Leach Park',
		address:`1108 E 28th St.
Vancouver, WA 98663`,
		size:'0.25 acres',
        image:'playground13.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'LeRoy Haagen Memorial Park',
		address:`13412 NE LeRoy Haagen Memorial Dr.
Vancouver, WA 98684`,
		size:'29.6 acres',
        image:'playground6.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:true,
			restroom:true,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Leverich Park',
		address:`4400 NE Leverich Park Way
Vancouver, WA 98663`,
		size:'16 acres',
        image:'playground9.webp',
		features:{
			benches:false,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:true,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:true,
			tennis:false,
			softball:false,
			discGolf:true,
		}
	},
	{
		name:'Liberty Park',
		address:`30249 Thompson Ave.
Vancouver, WA 98660`,
		size:'0.2 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Lieser Crest Park',
		address:`7510 Virginia Ln.
Vancouver, WA 98664`,
		size:'4.6 acres',
        image:'playground1.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Lieser School Park',
		address:`105 S Lieser Rd.
Vancouver, WA 98664`,
		size:'2 acres',
        image:'playground2.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Marine Park',
		address:`4501 SE Columbia Way
Vancouver, WA 98661`,
		size:'58.3 acres',
        image:'fountain.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:true,
			waterAccess:true,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:true,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Marrion Elementary School Park',
		address:`9801 NE 14th St.
Vancouver, WA 98664`,
		size:'5 acres',
        image:'playground4.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Marshall Park',
		address:`1015 E McLoughlin Blvd.
Vancouver, WA 98663`,
		size:'14 acres',
        image:'playground5.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:true,
			restroom:true,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:true,
			discGolf:false,
		}
	},
	{
		name:'Meadow Homes Park',
		address:`4500 E 18th St.
Vancouver, WA 98661`,
		size:'not available',
        image:'playground6.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Meadowbrook Marsh',
		address:`1901 NE 86th Ave.
Vancouver, WA 98664`,
		size:'3.5 acres',
        image:'trail1.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Memory/Mill Plain Park',
		address:`E. Evergreen Blvd
Vancouver, WA 98663`,
		size:'13.3 acres',
        image:'softball.webp',
		features:{
			benches:false,
			tables:true,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:true,
			waterAccess:false,
			swings:false,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:true,
			discGolf:false,
		}
	},
	{
		name:'MyPark Park',
		address:`3705 E 18th St.
Vancouver, WA 98661`,
		size:'0.37 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:true,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Nikkei Park',
		address:`5009 NE 135th Ave.
Vancouver, WA 98682`,
		size:'5 acres',
        image:'playground15.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:true,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Oakbrook Park',
		address:`3103 NE 99th Ave.
Vancouver, WA 98662`,
		size:'13.6 acres',
        image:'playground9.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:true,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Old Apple Tree Park',
		address:`112 Columbia Way
Vancouver, WA 98660`,
		size:'not available',
        image:'fort-vancouver.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:true,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Orchards West Park',
		address:`9201 NE 54th St.
Vancouver, WA 98662`,
		size:'13 acres',
        image:'playground9.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Peter S. Ogden Park',
		address:`415 W. Sixth St.
Vancouver, WA 98660`,
		size:'4.8 acres',
        image:'playground10.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Quarnberg Park',
		address:`2101 E 13th St.
Vancouver, WA 98661`,
		size:'3.5 acres',
        image:'playground11.webp',
		features:{
			benches:false,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:true,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Robert K. Starke Natural Park',
		address:`NE Park Plaza Dr.
Vancouver, WA 98684`,
		size:'not available',
        image:'trail1.webp',
		features:{
			benches:false,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Shumway Park',
		address:`3014 F St.
Vancouver, WA 98663`,
		size:'0.6 acres',
        image:'playground11.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Southcliff Park',
		address:`4506 Oregon Dr.
Vancouver, WA 98661`,
		size:'2.7 acres',
        image:'playground13.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'St. Helens Park',
		address:`4007 E. 13th St.
Vancouver, WA 98661`,
		size:'3.2 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Summer\'s Walk Neighborhood Park',
		address:`SE 17th St & SE 180th Ave.
Vancouver, WA 98683`,
		size:'4.8 acres',
        image:'playground1.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'The Downs Neighborhood Park',
		address:`3217 NE 62nd Ave.
Vancouver, WA 98661`,
		size:'3.2 acres',
        image:'playground2.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Tranquility Nature Area',
		address:`10506 NE 14th St.
Vancouver, WA 98664`,
		size:'5.6 acres',
        image:'playground3.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Van Vleet Park',
		address:`900 Flint Ave.
Vancouver, WA 98664`,
		size:'2.8 acres',
        image:'playground4.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Vancouver Waterfront Park',
		address:`115 SE Columbia
Way Vancouver, WA 98661`,
		size:'7.3 acres',
        image:'stanley-park.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:true,
			playground:false,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:true,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Village Woods',
		address:`17407 SE 34th St.
Vancouver, WA 98683`,
		size:'2.3 acres',
        image:'trail2.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:false,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:true,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Washington School Park',
		address:`2908 S St.
Vancouver, WA 98663`,
		size:'5 acres',
        image:'playground3.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Water Works Park',
		address:`2401 E Fourth Plain Blvd. Vancouver, WA 98661`,
		size:'24.5 acres',
        image:'paved1.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:false,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'West Minnehaha Neighborhood Park',
		address:`2502 NE 49th St.
Vancouver, WA 98663`,
		size:'3.2 acres',
        image:'playground6.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:true,
			pavedTrail:true,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:false,
			halfcourt:true,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Wildwood Park',
		address:`2808 SE Talton Ave.
Vancouver, WA 98683`,
		size:'4 acres',
        image:'playground7.webp',
		features:{
			benches:true,
			tables:false,
			playLawn:false,
			playground:true,
			pavedTrail:false,
			soccer:false,
			restroom:false,
			waterAccess:false,
			swings:true,
			multiuseField:true,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Wintler Community Park',
		address:`6400 SE Beach Dr.
Vancouver, WA 98661`,
		size:'12.5 acres',
        image:'paved2.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:false,
			playground:false,
			pavedTrail:true,
			soccer:false,
			restroom:true,
			waterAccess:true,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
	{
		name:'Wy\'East Park',
		address:`1112 SE 136th Ave.
Vancouver, WA 98683`,
		size:'24 acres',
        image:'playground8.webp',
		features:{
			benches:true,
			tables:true,
			playLawn:true,
			playground:true,
			pavedTrail:true,
			soccer:true,
			restroom:false,
			waterAccess:false,
			swings:false,
			multiuseField:false,
			halfcourt:false,
			fullcourt:false,
			skatePark:false,
			natureTrail:false,
			waterFountain:false,
			horseshoes:false,
			tennis:false,
			softball:false,
			discGolf:false,
		}
	},
]

const features = Object.keys(parks[0].features)

const featureDescriptions = {
    benches:"Benches",
    tables:"Picnic Tables",
    playLawn:"Grassy Play Area",
    playground:"Playground",
    pavedTrail:"Paved Trail",
    soccer:"Soccer Field",
    restroom:"Restroom",
    waterAccess:"Water(Lake/River) Access",
    swings:"Swing Set",
    multiuseField:"Multi-Use Field",
    halfcourt:"Basketball Half Court",
    fullcourt:"Basketball Full Court",
    skatePark:"Skate Park",
    natureTrail:"Nature Trail",
    waterFountain:"Water Fountain",
    horseshoes:"Horseshoes",
    tennis:"Tennis Court",
    softball:"Softball Field",
    discGolf:"Disc Golf Course",
}

function getMatchingParks(){
    return parks.filter((park)=>{
        for(let i=0; i < features.length; i++){
            if(filter[feature] && !park[feature])
                return false;
        }
        return true;
    })
}

let selection = getSelection()
if(selection === null) {selection = -1 }

const menu = document.querySelector('#menu');
const nav = document.querySelector('nav')

menu.addEventListener('click',()=>{
    menu.classList.toggle('open');
    nav.classList.toggle('open');
})

function getSelection(){
    return JSON.parse(localStorage.getItem('selection'))
}

function setSelection(value){
    selection = value
    localStorage.setItem('selection',value)
}
